### ISSUE TITLE
PN532 PowerDown

### ISSUE THREAD

**Issue by thiagohersan** [adafruit/Adafruit_NFCShield_I2C#13]
Hello !

I'm working on a project where I need to send data from an Android device to an Arduino through NFC.

Since we can't do that directly, my solutions was to just physically attach a MiFare Card to the shield and use it as an intermediary between Android and Arduino. Android writes to the card... Arduino reads from the card... user thinks it's magic... everyone is happy.

It works pretty well, but I have to power down the PN532 in order to write to the card while it's sitting on top of the shield coil.

So I created a disable() function that puts the PN532 in PowerDown mode, and an enable() function that wakes it up when I want to try reading a card.

If this is of value to the lib I would love to make a PR with my additions.

**Comment by tdicola** [comment]
I'm cleaning up old issues and will close this one since it's been around for a while without an update.  We've actually cleaned up this NFCShield_I2C library and integrated it into the PN532 library here: https://github.com/adafruit/Adafruit-PN532  Feel free to contribute any changes to that library in the future, thanks!
